name: Feature Request
description: New feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What do you want?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why
      placeholder: Why is this needed?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution